app = "pdd-flask"

[build]
  builtin = "python"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[vm]
  memory = 2048  # Increase memory for YOLO model
  cpu_kind = "shared"
  cpus = 1
